"""empty message

Revision ID: 1e27032b4362
Revises: f2e6703eaf5b
Create Date: 2022-01-15 13:45:56.866079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e27032b4362'
down_revision = 'f2e6703eaf5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('post', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_archived')
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
