"""empty message

Revision ID: 61b5edcae2cb
Revises: 8451138dbf98
Create Date: 2022-01-15 13:57:50.556466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b5edcae2cb'
down_revision = '8451138dbf98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('post', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_archived')
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
