"""empty message

Revision ID: 700329c2b067
Revises: d9329c5bd00f
Create Date: 2022-01-15 13:40:16.685147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700329c2b067'
down_revision = 'd9329c5bd00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('post', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_archived')
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
