"""empty message

Revision ID: 8fdec7142315
Revises: 61b5edcae2cb
Create Date: 2022-01-15 14:02:50.271512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdec7142315'
down_revision = '61b5edcae2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('post', sa.Column('is_archived', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_archived')
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
