"""empty message

Revision ID: f2e6703eaf5b
Revises: 700329c2b067
Create Date: 2022-01-15 13:43:57.027698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e6703eaf5b'
down_revision = '700329c2b067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('post', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_archived')
    op.alter_column('group', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
